apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppy-web
  labels:
    app: shoppy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shoppy
  template:
    metadata:
      labels:
        app: shoppy
    spec:
      containers:
      - name: shoppy-web
        image: ecommerce-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: "shoppy_db"
        - name: DB_USER
          value: "shoppy_user"
        - name: DB_PASSWORD
          value: "shoppy_pass"
        - name: DB_HOST
          value: "shoppy-db-service"
        - name: DB_PORT
          value: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppy-db
  labels:
    app: shoppy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppy-db
  template:
    metadata:
      labels:
        app: shoppy-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "shoppy_db"
        - name: POSTGRES_USER
          value: "shoppy_user"
        - name: POSTGRES_PASSWORD
          value: "shoppy_pass"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
