apiVersion: v1
kind: Service
metadata:
  name: shoppy-web-service
spec:
  selector:
    app: shoppy
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: shoppy-db-service
spec:
  selector:
    app: shoppy-db
  ports:
  - port: 5432
    targetPort: 5432
